version: '3'
services:
  flask-tutorial:
    image: flask-tutorial
    container_name: flask-tutorial
    ports:
      - "80:80"
    volumes:
      - ./app:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=80'
    command: flask run --host=0.0.0.0 --port=80
